### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by doi152** [zs-liu/GOC-VRPTW#4]
python main.py

Traceback (most recent call last):
  File "main.py", line 47, in <module>
    main()
  File "main.py", line 17, in main
    g_map = GlobalMap(read_dir=read_dir)
  File "C:\Users\user\OneDrive\Documents\tools\global_map.py", line 11, in __init__
    self.distance_table = dt.read_distance()
  File "C:\Users\user\OneDrive\Documents\tools\data_taker.py", line 11, in read_distance
    table = pd.read_csv(self.distance_time_dir, usecols=[1, 2, 3, 4])
  File "C:\Users\user\anaconda3\envs\test\lib\site-packages\pandas\io\parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\user\anaconda3\envs\test\lib\site-packages\pandas\io\parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\user\anaconda3\envs\test\lib\site-packages\pandas\io\parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "C:\Users\user\anaconda3\envs\test\lib\site-packages\pandas\io\parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\user\anaconda3\envs\test\lib\site-packages\pandas\io\parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'data/input_distance-time.csv'

**Comment by zsliu98** [comment]
Please refer to #3 .

**Comment by doi152** [comment]
may i know how the data looks like? I would just like to know the column title for the data that are required to test the code. Thank you

**Comment by zsliu98** [comment]
The [link](https://jdata.jd.com/html/detail.html?id=5) in #3 describes the format(columns) of all input files.
Cause it is a toy project, I recommend not using this project for study/research/production.
